### Семинар 3
В данном семинаре будут рассмотрены следующие темы:
 - Постановка задачи регрессии
 - Метрики задачи регрессии
 - Постановка задачи классификации
 - Метрики задачи классификации
 - Постановка задачи кластеризации
 - Объяснение алгоритма KNN
 - Предобработка данных для KNN
 - Имплементация алгоритма KNN
 - Подбор параметров для алгоритма KNN
 - Оценка качества реализованного алгоритма


### Постановка задачи регрессии
Задачи регрессии — это задачи машинного обучения при использовании числового целевого столбца. 

### Метрики задачи регрессии
- MAE
- MSE
- RMSE
- MAPE
- R2

In [17]:
import numpy as np
from sklearn import metrics

In [42]:
y = np.array([100, 150, 115, 125])
y_pred = np.array([96, 143, 120, 120])

In [43]:
# MAE
metrics.mean_absolute_error(y, y_pred)

np.float64(5.25)

In [44]:
np.abs(y - y_pred).sum() / len(y)

np.float64(5.25)

In [45]:
# MSE
metrics.mean_squared_error(y, y_pred)

np.float64(28.75)

In [46]:
((y - y_pred) ** 2).sum() / len(y)

np.float64(28.75)

In [47]:
# RMSE
metrics.root_mean_squared_error(y, y_pred)

np.float64(5.361902647381804)

In [49]:
np.sqrt(((y - y_pred) ** 2).sum() / len(y))

np.float64(5.361902647381804)

In [50]:
# R2
metrics.r2_score(y, y_pred)

0.9132075471698113

In [57]:
1 - (((y_pred - y) ** 2).sum() / ((y - y.mean()) ** 2).sum())

np.float64(0.9132075471698113)

### Постановка задачи Классификации
Классификация - задача, в которой множество объектов необходимо разделить некоторым образом на классы, при этом задано конечное множество объектов, для которых известно, к каким классам они относятся (выборка), но классовая принадлежность остальных объектов неизвестна.

### Метрики задачи классификации

- Accuracy
- Precision
- Recall
- F1-score
- ROC-AUC

In [75]:
y = np.array([1, 0, 1, 1, 1, 0, 0])
y_pred = np.array([0, 0, 1, 1, 1, 1, 1])

In [76]:
# Accuracy
metrics.accuracy_score(y, y_pred)

0.5714285714285714

In [77]:
(y == y_pred).mean()

np.float64(0.5714285714285714)

In [78]:
# Precision
metrics.precision_score(y, y_pred)

np.float64(0.6)

In [94]:
tp = ((y == 1) & (y_pred == 1)).sum()
fp = ((y == 0) & (y_pred == 1)).sum()
fn = y.sum()

In [99]:
precision = tp / (tp + fp)
precision

np.float64(0.6)

In [100]:
# Recall
metrics.recall_score(y, y_pred)

np.float64(0.75)

In [101]:
recall = tp / fn
recall

np.float64(0.75)

In [98]:
# F1
metrics.f1_score(y, y_pred)

np.float64(0.6666666666666666)

In [103]:
f1 = 2 * (precision * recall) / (precision + recall)
f1

np.float64(0.6666666666666665)

In [137]:
y = np.array([1, 0, 1, 0])
y_pred = np.array([0, 0, 1, 0])

In [138]:
# ROC-AUC
metrics.roc_auc_score(y, y_pred)

np.float64(0.75)

In [139]:
print(y_pred, y, sep="\n")

[0 0 1 0]
[1 0 1 0]


Упорядочим наблюдения по **убыванию** ответов алгоритма.

In [140]:
y = np.array([1, 1, 0, 0])
y_pred = np.array([1, 0, 0, 0])
print(y, y_pred, sep="\n")

[1 1 0 0]
[1 0 0 0]


Разобьём единичный квадрат на $(m, n)$ частей, где $m$ – число 1 в $y$, $n$ – число нулей. Стартуем из точки $(0, 0)$. Если значение $y$ равно 1, делаем шаг вверх, а если 0 – вправо. Понятно, что конечная точка нашего маршрута – точка $(1, 1)$.

**Важный момент:** если у нескольких объектов значения предсказаний равны, а $y$ – различны, то мы должны сделать ход \"по диагонали\".

Если построить кривую по этому алгоритму, то получим:

In [143]:
1 - 0.5 / 2

0.75

In [146]:
y = np.array([1, 0, 0, 0])
y_pred = np.array([0, 1, 0, 0])
print(y, y_pred, sep="\n")

[1 0 0 0]
[0 1 0 0]
